namespace Crestron.RAD.Common.Enums
{
    public enum SecuritySystemStateObjects
    {
        KeypadStatusText,
        KeypadLeds,
        SecuritySystemStates,
        Features,
        Connection,
        AuxiliaryButtonLedState,
        Login,
        SoftwareVersion,
        SoftwareVersionDifferences,
        ResourceStatus,
        ResourceState,
        ResourceCustomFeature,
        SecuritySystemCustomFeature,
        SystemStatus,
        Log,
        Info,
        Heartbeat,
        DeviceSetup,
        SystemSetup,
        Message,
        SoftButton,
        SoftButtonFeedback,
        SoftLED,
        SoftLEDFeedback,
        ExitTime,
    }
}