namespace Crestron.RAD.Common.Enums
{
	public enum CommonFeatureSupport
	{
		SupportsArrowKeys = 1,
		SupportsAsterisk = 2,
		SupportsBack = 3,
		SupportsChangeChannel = 4,
		SupportsChangeVolume = 5,
		SupportsChannelFeedback = 6,
		SupportsClear = 7,
		SupportsColorButtons = 8,
		SupportsCoolDownTime = 9,
		SupportsDash = 10,
		SupportsDisconnect = 11,
		SupportsDiscreteMute = 12,
		SupportsDiscretePower = 13,
		SupportsDvrCommand = 14,
		SupportsEnter = 15,
		SupportsExit = 16,
		SupportsFavorite = 17,
		SupportsForwardScan = 18,
		SupportsForwardSkip = 19,
		SupportsGuide = 20,
		SupportsHome = 21,
		SupportsInfo = 22,
		SupportsKeypadBackSpace = 23,
		SupportsKeypadNumber = 24,
		SupportsLast = 25,
		SupportsLetterKeys = 26,
		SupportsLive = 27,
		SupportsMenu = 28,
		SupportsMute = 29,
		SupportsMuteFeedback = 30,
		SupportsPageChange = 31,
		SupportsPause = 32,
		SupportsPeriod = 33,
		SupportsPlay = 34,
		SupportsPound = 35,
		SupportsPowerFeedback = 36,
		SupportsReconnect = 37,
		SupportsRecord = 38,
		SupportsRepeat = 39,
		SupportsReplay = 40,
		SupportsReturn = 41,
		SupportsReverseScan = 42,
		SupportsReverseSkip = 43,
		SupportsSetChannel = 44,
		SupportsSetVolume = 45,
		SupportsSpeedSlow = 46,
		SupportsStop = 47,
		SupportsThumbsDown = 48,
		SupportsThumbsUp = 49,
		SupportsTogglePower = 50,
		SupportsVolumePercentFeedback = 51,
		SupportsWarmUpTime = 52,
		SupportsFeedback = 53,
		SupportsPlayBackStatusFeedback = 54,
		SupportsTrackFeedback = 55,
		SupportsChapterFeedback = 56,
		SupportsTrackElapsedTimeFeedback = 57,
		SupportsTrackRemainingTimeFeedback = 58,
		SupportsChapterElapsedTimeFeedback = 59,
		SupportsChapterRemainingTimeFeedback = 60,
		SupportsTotalElapsedTimeFeedback = 61,
		SupportsTotalRemainingTimeFeedback = 62,
		SupportsAudio = 63,
		SupportsDisplay = 64,
		SupportsEject = 65,
		SupportsOptions = 66,
		SupportsSubtitle = 67,
		SupportsInputFeedback = 68,
		SupportsLampHours = 69,
		SupportsSetInputSource = 70,
		SupportsPanAndTilt = 71,
		SupportsZoom = 72,
		SupportsManualFocus = 73,
		SupportsAutoFocus = 74,
		SupportsIrRemoteEmulation = 75,
		SupportsMeetings = 76,
		SupportsSelfView = 77,
		SupportsSelfViewPosition = 78,
		SupportsDualVideo = 79,
		SupportsPresentationPip = 80,
		SupportsPictureMode = 81,
		SupportsLocality = 82,
		SupportsToggleVideoMute = 83,
		SupportsSwitching = 84,
		SupportsToggleEnergyStar = 85,
		SupportsDiscreteEnergyStar = 86,
		SupportsEnergyStarFeedback = 87,
		SupportsDiscreteVideoMute = 88,
		SupportsVideoMuteFeedback = 89,
		SupportsOnScreenDisplayFeedback = 90,
		SupportsFarEndCameraPresetStore = 91,
		SupportsInput4Connector = 92,
		SupportsFarEndPresentationSourceSelect = 93,
		SupportsMultipointControl = 94,
		SupportsIREmulation = 95,
		SupportsMonitorPresentation = 96,
		SupportsPictureLayout = 97,
		SupportsPan = 98,
		SupportsTilt = 99,
		SupportsMicMute = 100,
		SupportsRecentCallsDialing = 110,
		SupportsPopUpMenu = 111,
		SupportsTopMenu = 112,
		SupportsSelect = 113,
		//**AVR IAudio Additional Support values
		SupportsToneControlFeedback = 114,
		SupportsDiscreteToneControl = 115,
		SupportsToggleToneControl = 116,
		SupportsBassFeedback = 117,
		SupportsBassDbFeedback = 118,
		SupportsTrebleFeedback = 119,
		SupportsTrebleDbFeedback = 120,
		SupportsSetBass = 121,
		SupportsChangeBass = 122,
		SupportsSetTreble = 123,
		SupportsChangeTreble = 124,
		SupportsLoudnessFeedback = 125,
		SupportsDiscreteLoudness = 126,
		SupportsToggleLoudness = 127,
		//**AVR ISurround Additional Supports values
		SupportsSurroundModeFeedback = 128,
		SupportsSurroundModeCycle = 129,
		//**AVR ITuner Additional Supports Values
		SupportsTunerFeedback = 130,
		SupportsChangeFrequency = 131,
		SupportsSetFrequency = 132,
		SupportsAutoFrequency = 133,
		SupportsFrequencyBand = 134,
		SupportsDiscreteFrequencyBand = 135,
		SupportsPresetRecall = 136,
		SupportsPresetStore = 137,
		//**Video Server Additional Supports Values
		SupportsSearch = 138,
		SupportsSetAudioInputSource = 139,
		SupportsSetVideoInputSource = 140,
		SupportsAudioInputFeedback = 141,
		SupportsVideoInputFeedback = 142,
		SupportsSetAudioOutputSource = 143,
		SupportsSetVideoOutputSource = 144,
		SupportsAudioOutputFeedback = 145,
		SupportsVideoOutputFeedback = 146,
		SupportsUsername = 147,
		SupportsPassword = 148,
		//**AVR Media Sources Support values
		SupportsSirius = 149,
		SupportsXm = 150,
		SupportsSiriusXm = 151,
		SupportsHdRadio = 152,
		SupportsInternetRadio = 153,
		SupportsLastFm = 154,
		SupportsPandora = 155,
		SupportsRhapsody = 156,
		SupportsChangePreset = 157,
		//** IMediaTransport2
		SupportsPlayPause = 158,
		//**IMediaSource2
		SupportsSpotify = 159,
		SupportsYouTube = 160,
		SupportsYouTubeTv = 161,
		SupportsNetflix = 162,
		SupportsHulu = 163,
		SupportsDirectvNow = 164,
		SupportsAmazonVideo = 165,
		SupportsPlaystationVue = 166,
		SupportsSlingTv = 167,
		SupportsAirplay = 168,
		SupportsGoogleCast = 169,
		SupportsDlna = 170,
		SupportsTidal = 171,
		SupportsDeezer = 172,
		SupportsCrackle = 173,
		SupportsOnDemand = 174,
		SupportsGooglePlay = 175,
		SupportsBluetooth = 176,
		SupportsTivo = 177,
		SupportsRSkip = 178,
		SupportsFSkip = 179,
		//**ISecurity
		SupportsKeypadEmulation = 180,
		SupportsLogin = 181,
		SupportsUDLLogin = 182,
		SupportsRequestSoftwareVersion = 183,
		SupportsRequestSoftwareVersionDifferences = 184,
		//SupportsRequestResourceStatus = 185,
		SupportsRequestSystemStatus = 186,
		SupportsRequestResourceName = 187,
		SupportsRequestResourcePermission = 188,
		SupportsBypassZones = 189,
		SupportsUnbypassZones = 190,
		SupportsResourceArmAway = 191,
		SupportsResourceArmAwayInstant = 192,
		SupportsResourceArmAwayDelayed = 193,
		SupportsResourceArmDelayed = 194,
		SupportsResourceArmInstant = 195,
		SupportsResourceArmStay = 196,
		SupportsResourceArmStayInstant = 197,
		SupportsResourceArmStayDelayed = 198,
		SupportsDisarm = 199,
		SupportsDisarmResource = 200,
		SupportsRequestLog = 201,
		SupportsRequestLogSetAmount = 202,
		SupportsRequestFeatures = 203,
		SupportsRequestSetup = 204,
		SupportsRequestAreaInfo =  205,
		SupportsRequestZoneInfo = 206,
		SupportsRequestOutputInfo =  207,
		SupportsRequestDoorInfo = 208,
		SupportsRequestDeviceInfo = 209,
		//SupportsRequestAreaCount = 210,
		//SupportsRequestZoneCount = 211,
		//SupportsRequestOutputCount = 212,
		//SupportsRequestDoorCount = 213,
		//SupportsRequestDeviceCount  =214,
		SupportsRequestAreaResourceStatus = 215,
		SupportsRequestZoneResourceStatus = 216,
		SupportsRequestOutputResourceStatus = 217,
		SupportsRequestDoorResourceStatus = 218,
		SupportsRequestDeviceResourceStatus = 219,
		SupportsSetResourceState = 220,
		SupportsRequestBypassedZones = 221,
		SupportsSilenceBells = 222,
		SupportsResetSensors = 223,
		SupportsSubscribeResourceOnOffState = 224,
		SupportsSubscribeResourceReadyState = 225,
		SupportsSubscribeResourceGeneralState = 226,
		SupportsSubscribeDeviceMessages = 227,
		SupportsSubscribeDeviceLogging = 228,
		SupportsSubscribeDeviceConfigurationChange = 229,
		SupportsSubscribe = 230,
		SupportsRequestAlarm = 231,
		SupportsRequestAreasNotReadyToArm = 232,
		SupportsArmAll = 233,
		SupportsDisarmAll = 234,
		SupportsBypassAll = 235,
		SupportsUnbypassAll = 236,
		SupportsKeypadStatusText = 237,
		SupportsUpDown = 238,
		SupportsLeftRight = 239,
		SupportsRequestUsers = 240,
		SupportsRequestAreaAlarm = 241,
		SupportsRequestZoneAlarm = 242,
		SupportsRequestTamper = 243,
		SupportsRequestAlarmMemory = 244,
		SupportsRequestAreaAlarmMemory = 245,
		SupportsRequestZoneAlarmMemory = 246,
		SupportsRequestFireAlarm = 247,
		SupportsRequestFireAlarmMemory = 248,
		SupportsArm = 249,
		SupportsRequestAreaExitTime = 250,
		SupportsRequestAreaInExitDelay = 251,
		SupportsRequestAreaInEntryDelay = 252,
		/// <summary>
		/// Used by <see cref="Crestron.RAD.Common.Interfaces.IHardwareDiagnostics.SupportsTemperatureFeedback"/>.
		/// </summary>
		SupportsTemperatureFeedback = 251,

		/// <summary>
		/// Used by <see cref="Crestron.RAD.Common.Interfaces.ISpeakerProtect.SupportsSpeakerProtectFeedback"/>.
		/// </summary>
		SupportsSpeakerProtectFeedback = 252,

		/// <summary>
		/// Used by <see cref="Crestron.RAD.Common.Interfaces.ISpeakerProtect.SupportsDiscreteSpeakerProtect"/>.
		/// </summary>
		SupportsDiscreteSpeakerProtect = 253,

		/// <summary>
		/// Used by <see cref="Crestron.RAD.Common.Interfaces.ISpeakerProtect.SupportsSpeakerProtectToggle"/>.
		/// </summary>
		SupportsSpeakerProtectToggle = 254,

		/// <summary>
		/// Used by <see cref="Crestron.RAD.Common.Interfaces.IAudioVideoExtender.SupportsAudioIsClippingFeedback"/>.
		/// </summary>
		SupportsAudioIsClippingFeedback = 255,

		/// <summary>
		/// Used by <see cref="Crestron.RAD.Common.Interfaces.IAudioVideoExtender.SupportsDcFaultStateFeedback"/>.
		/// </summary>
		SupportsDcFaultStateFeedback = 256    }
}